<?php

/**
 * Class PdoDriver
 */
class PdoDriver extends DBDriver
{
    public function db_connect()
    {
        return parent::db_connect(); // TODO: Change the autogenerated stub
    }

    public function trans_begin()
    {
        // TODO: Implement trans_begin() method.
    }

    public function trans_commit()
    {
        // TODO: Implement trans_commit() method.
    }

    public function trans_rollback()
    {
        // TODO: Implement trans_rollback() method.
    }

}